# Generated by Django 1.10.6 on 2017-03-17 18:27
from django.db import migrations, models

try:
    import django.contrib.auth.validators

    extra_kwargs = {
        "validators": [django.contrib.auth.validators.ASCIIUsernameValidator()]
    }
except ImportError:
    extra_kwargs = {}


class Migration(migrations.Migration):

    dependencies = [("users", "0013_profile_event_reminder_time")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                verbose_name="username",
                **extra_kwargs,
            ),
        )
    ]
